spring:
  application:
    name: securityjwt106
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/Learn
    username: postgres
    password: new_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
      enabled: true
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      cache: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
